package com.halo.moontone.ui.theme

import androidx.compose.ui.graphics.Color

// Dark fallback (MoonTone brand: midnight blue + electric teal)
val MoonTonePrimaryDark = Color(0xFFB7C4FF)
val MoonToneOnPrimaryDark = Color(0xFF1A2560)
val MoonTonePrimaryContainerDark = Color(0xFF323D7A)
val MoonToneOnPrimaryContainerDark = Color(0xFFDEE1FF)
val MoonToneSecondaryDark = Color(0xFF7FD8C8)
val MoonToneOnSecondaryDark = Color(0xFF00382F)
val MoonToneSecondaryContainerDark = Color(0xFF005045)
val MoonToneOnSecondaryContainerDark = Color(0xFFA0F2E2)
val MoonToneTertiaryDark = Color(0xFFF0B8C8)
val MoonToneOnTertiaryDark = Color(0xFF4A2531)
val MoonToneTertiaryContainerDark = Color(0xFF643B47)
val MoonToneOnTertiaryContainerDark = Color(0xFFFFD9E2)
val MoonToneErrorDark = Color(0xFFFFB4AB)
val MoonToneOnErrorDark = Color(0xFF690005)
val MoonToneErrorContainerDark = Color(0xFF93000A)
val MoonToneOnErrorContainerDark = Color(0xFFFFDAD6)
val MoonToneBackgroundDark = Color(0xFF111318)
val MoonToneOnBackgroundDark = Color(0xFFE7E7EC)
val MoonToneSurfaceDark = Color(0xFF17191F)
val MoonToneOnSurfaceDark = Color(0xFFE7E7EC)
val MoonToneSurfaceVariantDark = Color(0xFF252832)
val MoonToneOnSurfaceVariantDark = Color(0xFFC6C6D0)
val MoonToneOutlineDark = Color(0xFF90909A)

// Light fallback
val MoonTonePrimaryLight = Color(0xFF4556B8)
val MoonToneOnPrimaryLight = Color(0xFFFFFFFF)
val MoonTonePrimaryContainerLight = Color(0xFFDEE1FF)
val MoonToneOnPrimaryContainerLight = Color(0xFF00105C)
val MoonToneSecondaryLight = Color(0xFF006B5D)
val MoonToneOnSecondaryLight = Color(0xFFFFFFFF)
val MoonToneSecondaryContainerLight = Color(0xFFA0F2E2)
val MoonToneOnSecondaryContainerLight = Color(0xFF00201B)
val MoonToneTertiaryLight = Color(0xFF7D5260)
val MoonToneOnTertiaryLight = Color(0xFFFFFFFF)
val MoonToneTertiaryContainerLight = Color(0xFFFFD9E2)
val MoonToneOnTertiaryContainerLight = Color(0xFF31111D)
val MoonToneErrorLight = Color(0xFFBA1A1A)
val MoonToneOnErrorLight = Color(0xFFFFFFFF)
val MoonToneErrorContainerLight = Color(0xFFFFDAD6)
val MoonToneOnErrorContainerLight = Color(0xFF410002)
val MoonToneBackgroundLight = Color(0xFFFBF8FF)
val MoonToneOnBackgroundLight = Color(0xFF1B1B21)
val MoonToneSurfaceLight = Color(0xFFFBF8FF)
val MoonToneOnSurfaceLight = Color(0xFF1B1B21)
val MoonToneSurfaceVariantLight = Color(0xFFE3E1EC)
val MoonToneOnSurfaceVariantLight = Color(0xFF46464F)
val MoonToneOutlineLight = Color(0xFF777680)
